# Generated by Django 5.1.7 on 2025-04-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Incident',
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
        migrations.AddField(
            model_name='firestation',
            name='city',
            field=models.CharField(default='Puerto Princesa', max_length=100),
            preserve_default=False,
        ),
    ]
