# Generated by Django 5.1.7 on 2025-04-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0002_delete_incident_delete_locations_firestation_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firestation',
            name='city',
            field=models.CharField(default='Puerto Princesa', max_length=100),
        ),
    ]
